FROM python:3.9-slim-buster

ENV PYTHONUNBUFFERED 1

WORKDIR /bakas
COPY . .

RUN pip install --upgrade pip
RUN pip install -r/bakas/requirements.txt

CMD ["gunicorn","backend.wsgi:application","--bind","0.0.0.0:8000"]


